# Basic
name:               "Li@ng"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "coverpage"
    href:           "http://liang.fi"
  #- name:           "About"
  #  href:           "/about"
  #- name:           "Projects"
  #  href:           "/projects"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

future:             true
